[package]
name = "utfdump_wasm"
version = "0.1.0"
edition = "2021"
rust-version = "1.70.0"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
utfdump = { path = "../lib" }
wasm-bindgen = "0.2.86"
